server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/app_coding_bat
    username: turayevhasan
    password: 2003
    driver-class-name: org.postgresql.Driver
  jpa:
#    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        enable_lazy_load_no_trans: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  config:
    import:

  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

  mail:
    host: 'smtp.gmail.com'
    port: 587
    username: 'turayevhasan2003@gmail.com'
    password: 'tiii chrr wrtz tnak'
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

application:
  host: "http://localhost:${server.port}"

  file:
    upload-path: "E:/PROJECT_DOWNLOAD_FILES/"

  jwt:
    secret-key: '31321Jwt21cret76575646Key131231wt21cret76575646Key1312311321Jwt21cret76575646Key131231wt21cret76575646Key131231'
    access-token-exp: 86400000 # a day
    refresh-token-exp: 24096000000 # 7 days
  mail:
    from: 'appcodingbat@info.com'
    activate-url: '${application.host}/api/v1/auth/activate/'

logging:
  config: classpath:log-conf/logback-spring.xml